# Font settings

font_family Maple Mono Light
font_size 10.0
enable_ligatures yes

# Anti-aliasing and font rendering settings
antialiasing true
subpixel_antialiasing rgb
hinting full
kerning true
line_height 1.15
line_spacing 0.95
dpi 96
