"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 4, 3]
sort_by = "natural"
sort_dir_first = true
show_hidden = true

[opener]
folder = [
  { run = 'open "$@"', orphan = true, desc = "Finder", for = "macos" },
  { run = 'forklift "$@"', orphan = true, desc = "ForkLift", for = "macos" },
  { run = 'nvim "$@"', block = true, desc = "neovim", for = "macos" },
  { run = 'lazygit -p "$1"', block = true, desc = "lazygit", for = "macos" },
  { run = 'cursor "$@"', orphan = true, desc = "Cursor", for = "macos" },
]
text = [
  { run = '$EDITOR "$@"', block = true, desc = "$EDITOR (nvim)", for = "macos" },
  { run = 'nvim "$@"', block = true, desc = "neovim", for = "macos" },
  { run = 'cursor "$@"', orphan = true, desc = "Cursor", for = "macos" },
  { run = 'open "$@"', orphan = true, desc = "default app", for = "macos" },
]
document = [
  { run = 'open "$@"', orphan = true, desc = "Preview/default app", for = "macos" },
]
image = [{ run = 'open "$@"', orphan = true, desc = "Preview", for = "macos" }]
video = [
  { run = 'open "$@"', orphan = true, desc = "QuickTime/default app", for = "macos" },
]
audio = [
  { run = 'open "$@"', orphan = true, desc = "Music/default app", for = "macos" },
]
archive = [
  { run = 'open "$@"', orphan = true, desc = "Archive Utility", for = "macos" },
]
fallback = [
  { run = 'open "$@"', orphan = true, desc = "system default", for = "macos" },
]

[open]
rules = [
  { name = "*/", use = "folder" },
  { mime = "text/*", use = "text" },
  { mime = "image/*", use = "image" },
  { mime = "video/*", use = "video" },
  { mime = "application/octet-stream", use = "video" },
  { mime = "audio/*", use = "audio" },
  { mime = "inode/x-empty", use = "text" },
  { mime = "application/json", use = "text" },
  { mime = "application/zip", use = "archive" },
  { mime = "application/gzip", use = "archive" },
  { mime = "application/x-bzip", use = "archive" },
  { mime = "application/x-bzip2", use = "archive" },
  { mime = "application/x-tar", use = "archive" },
  { mime = "application/x-7z-compressed", use = "archive" },
  { mime = "application/x-rar", use = "archive" },
  { mime = "application/pdf", use = "document" },
  { mime = "application/epub+zip", use = "document" },
  { mime = "application/x-mobipocket-ebook", use = "document" },
  { mime = "*", use = "fallback" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
