input {
    kb_layout = us

    # disable mouse acceleration
    accel_profile = flat

    # focus follows mouse position
    follow_mouse = 1

    numlock_by_default = true

    # enable if you want to use the touchpad

    # touchpad {
    #     natural_scroll = yes
    #     disable_while_typing = true
    #     scroll_factor = 1
    # }
}
